import React, { PureComponent } from 'react'
import {Popover} from 'antd';
export default class CommandKey extends PureComponent {
	render() {
		return (
			<Popover
					content={
						<div className="key-list">
							<div>
								<span>保存</span>
								<span>⌘/ctrl+S</span>
							</div>
							<div>
								<span>撤销</span>
								<span>⌘/ctrl+Z</span>
							</div>
							<div>
								<span>回退</span>
								<span>⌘/ctrl+shift+Z</span>
							</div>
							<div>
								<span>插入子节点</span>
								<span>Tab</span>
							</div>
							<div>
								<span>插入同级节点</span>
								<span>Enter</span>
							</div>
							<div>
								<span>复制</span>
								<span>⌘/ctrl+C</span>
							</div>
							<div>
								<span>剪切</span>
								<span>⌘/ctrl+X</span>
							</div>
							<div>
								<span>粘贴</span>
								<span>⌘/ctrl+V</span>
							</div>
							<div>
								<span>折叠</span>
								<span>F</span>
							</div>
							<div>
								<span>编辑</span>
								<span>Space</span>
							</div>
							<div>
								<span>结束编辑</span>
								<span>Enter</span>
							</div>
							<div>
								<span>退出编辑</span>
								<span>Esc</span>
							</div>
							<div>
								<span>换行</span>
								<span>shift+Space</span>
							</div>
							<div>
								<span>加粗</span>
								<span>ctrl+B</span>
							</div>
							<div>
								<span>斜体</span>
								<span>ctrl+I</span>
							</div>
							<div>
								<span>移动节点</span>
								<span>方向键</span>
							</div>
							<div>
								<span>脑图居中</span>
								<span>C</span>
							</div>
							<div>
								<span>移动脑图</span>
								<span>W/A/S/D</span>
							</div>
							<div>
								<span>放大缩小</span>
								<span>ctrl+鼠标滚轮</span>
							</div>
						</div>
					}
				>
					{/* <Icon type="question-circle" /> */}
					<i className="iconfont icon-keyboard shortcut"></i>
				</Popover>
		)
	}
}
